### ISSUE TITLE
Cannot open the program anymore

### ISSUE THREAD

**Issue by fixx1983** [rowak/nanoleaf-desktop#10]
Today I tried to open Nanoleaf for Desktop but it simply does nothing, exe and jar versions.

Trying to load the jar from cmd i receive this output:

```
java.lang.IllegalArgumentException: setSelectedIndex: 2 out of bounds
        at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
        at io.github.rowak.nanoleafdesktop.ui.panel.AmbilightPanel.loadUserSettings(AmbilightPanel.java:259)
        at io.github.rowak.nanoleafdesktop.ui.panel.AmbilightPanel.<init>(AmbilightPanel.java:60)
        at io.github.rowak.nanoleafdesktop.Main.initTabbedPane(Main.java:756)
        at io.github.rowak.nanoleafdesktop.Main.initUI(Main.java:655)
        at io.github.rowak.nanoleafdesktop.Main.<init>(Main.java:113)
        at io.github.rowak.nanoleafdesktop.Main$10.run(Main.java:837)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by rowak** [comment]
I just have a few questions:
- What version of the app are you running? Is it a debug version?
- How many monitors do you have connected?
- Could you upload your preferences.txt file? This file stores all the app data. To find it, press windows key + R then enter "%AppData%" and navigate to the folder "Nanoleaf for Desktop".

The error you posted suggests that the app is having trouble reading your data file. If this is the case, you can try deleting the file and let the app generate a new one for you. You will have to set up your devices again though.

**Comment by fixx1983** [comment]
Now I have a single monitor build, before I was two.

I tried all the versions, included debug one.

Anyway delete the preferences file worked. Could the issue be that i moved from a two monitors config to a single monitor one?

**Comment by rowak** [comment]
Aha!
Yes, that would definitely cause this to happen. If you had your second monitor set as the selected monitor then changed your config to only have one monitor, when the app goes to get the monitor info (resolution, etc) it fails because the monitor doesn't exist.
Thanks for reporting this. I'll get this issue and other related ones fixed in the next release!

**Comment by fixx1983** [comment]
Oh, so it was my fault! Thanks for your support!

**Comment by rowak** [comment]
Well, it was more my fault for not foreseeing and fixing this issue. No problem!
