### ISSUE TITLE
0.8.2 version won't open

### ISSUE THREAD

**Issue by fixx1983** [rowak/nanoleaf-desktop#11]
Tried to update to 0.8.2 version, exe version and jar doesn't work. No popup at all, and no presence of the program in Task Manager. Roll back to 0.8.1 made the magic and works like a charm

Log:
```
java.lang.NullPointerException
        at io.github.rowak.nanoleafdesktop.tools.BasicEffects.getBasicEffects(BasicEffects.java:127)
        at io.github.rowak.nanoleafdesktop.Main.initEffectsPanels(Main.java:729)
        at io.github.rowak.nanoleafdesktop.Main.initUI(Main.java:659)
        at io.github.rowak.nanoleafdesktop.Main.<init>(Main.java:124)
        at io.github.rowak.nanoleafdesktop.Main$9.run(Main.java:911)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by rowak** [comment]
Give [this version](https://ufile.io/tttq7n2j) a try, it should have fixed the problem (at least this specific error).

**Comment by fixx1983** [comment]
Yes, it works, apart from Basic Effects section that does nothing

**Comment by rowak** [comment]
Do you see any effects in the basic effects section or just nothing? If you do see effects, what happens when you left and/or right click on them?

**Comment by fixx1983** [comment]
I see the names of the Basic Effects, but when I click simply they does nothing. Everything else works good

**Comment by rowak** [comment]
Is there any error log when loading up the app or when you click on the effects?

**Comment by fixx1983** [comment]
Nothing, just does absolutely nothing

**Comment by rowak** [comment]
I forgot to ask: do you have the aurora or canvas lights? It's possible that the canvas behaves differently with these effects. Regardless of which device you have, give [this version](https://ufile.io/td7icah5) a try.

If you're still not seeing anything happen, check the console output. When the effect data is sent you should see the message "\*\*\*DISPLAYING EFFECT <effect_name>\*\*\*" (only on v0.8.3-debug.2).

**Comment by fixx1983** [comment]
I've Aurora ones. Anyway i deleted all of the versions, removed the preferences.txt and redownloaded 0.8.3 debug and now it works. What a mistery

**Comment by rowak** [comment]
Very strange :/
Sounds like some kind of corruption in the data file. I'll do some searching later to try and track down any code that might cause corruption.
