### ISSUE TITLE
Cannot open program 0.8.3

### ISSUE THREAD

**Issue by joshloh** [rowak/nanoleaf-desktop#12]
I couldn't open the program, it looks like it might be related to a previous issue.
https://github.com/rowak/nanoleaf-desktop/issues/10

I tried doing a similar thing here, and deleting the preferences.txt file fixed it. However, before the fix, when trying to run it through a bash prompt, I got the following error.

```$ java.lang.ArrayIndexOutOfBoundsException: 1
        at io.github.rowak.nanoleafdesktop.tools.PropertyManager.getProperty(Pro                                                                                                                                  pertyManager.java:42)
        at io.github.rowak.nanoleafdesktop.Main.<init>(Main.java:116)
        at io.github.rowak.nanoleafdesktop.Main$9.run(Main.java:912)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP                                                                                                                                  rivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

I'm not sure exactly what the cause was, but I, like the other person having this issue, swap between having a 1/2 monitor setup, so perhaps the issue from back then was not fully fixed?

I'm happy to help out with further diagnosing and fixing the problem btw! Let me know if you need anymore details or need me to try to recreate it.

**Comment by rowak** [comment]
I think you're right, it seems likely that this issue is related to #10. However, I just did some testing and the app seems to work as intended when switching between monitors for me. If you have monitor 2 or higher selected then the current monitor should revert to the default when the monitor is disconnected. As I mentioned in #10, this issue could also have been caused by one of many other unknown bugs that might cause the data file to be unreadable.

Did this issue just start happening when you updated to 0.8.3? What version were you on just before updating (if applicable)?

From what I can read in the error you posted, this issue appears to be different from the one posted in #10, and unfortunately it seems to missing some important information that appears to be cut off from the top. If possible, could you try recreating the issue to not only see if it happens consistently, but also to see if you can get the full error log? The error log should start off with the name of the error, for example "java.lang.NullPointerException". This information will help me find the exact cause and location of the error.

Thanks!
